// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCkHpBjq7YkdAJ3-sSplYq_7R03YG9lBQ0',
    appId: '1:661483828695:web:fdee33b8da408c0b424792',
    messagingSenderId: '661483828695',
    projectId: 'chatapp-3850f',
    authDomain: 'chatapp-3850f.firebaseapp.com',
    storageBucket: 'chatapp-3850f.appspot.com',
    measurementId: 'G-XWG4D7T83H',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBX1Hn3dQpyyt81sag_6zIHzuhLg6L37eA',
    appId: '1:661483828695:android:fd7bab6e3bedb696424792',
    messagingSenderId: '661483828695',
    projectId: 'chatapp-3850f',
    storageBucket: 'chatapp-3850f.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCeC-bUM1Pb-ohcHEPG5WVMghgGEgcoInc',
    appId: '1:661483828695:ios:ad76842004001e35424792',
    messagingSenderId: '661483828695',
    projectId: 'chatapp-3850f',
    storageBucket: 'chatapp-3850f.appspot.com',
    iosBundleId: 'com.example.chatApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCeC-bUM1Pb-ohcHEPG5WVMghgGEgcoInc',
    appId: '1:661483828695:ios:f3fda99fe42fdb93424792',
    messagingSenderId: '661483828695',
    projectId: 'chatapp-3850f',
    storageBucket: 'chatapp-3850f.appspot.com',
    iosBundleId: 'com.example.chatApp.RunnerTests',
  );
}
